name: rikerio-ethercat # you probably want to 'snapcraft register <name>'
version: '1.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: EtherCAT Master for RikerIO # 79 char long summary
description: |
    EtherCAT Master implementation for the RikerIO Server, using the Simple
    Open EtherCAT Master (SOEM).

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
    rikerio-ethercat:
        command: ethercat

parts:
  master:
    # See 'snapcraft plugins'
    plugin: cmake
    configflags:
      - -DCMAKE_BUILD_TYPE=Release
      - -DWITH_RIO=ON
